// LLM Council - PM2 Ecosystem Configuration
// Auto-generated by Claude Code Elite
// This project uses Docker Compose for all services
// Start: pm2 start ecosystem.config.js OR docker-compose up -d

module.exports = {
  apps: [
    {
      name: 'llm-council-stack',
      script: 'docker',
      args: 'compose up',
      cwd: './',
      watch: false,
      autorestart: false, // Docker handles restarts
      // Alternative: run frontend separately for hot reload
    },
    // Uncomment below to run frontend outside Docker (better HMR)
    // {
    //   name: 'llm-council-frontend',
    //   cwd: './frontend',
    //   script: 'npm',
    //   args: 'run dev',
    //   watch: false,
    //   env: {
    //     NODE_ENV: 'development',
    //   },
    // },
  ],
};
